spring:
  config:
    activate:
      on-profile: prod

  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  datasource-replica:
    url: ${DB_REPLICA_URL}
    username: ${DB_REPLICA_USER}
    password: ${DB_REPLICA_PASS}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASS}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:true}

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

app:
  messaging:
    provider: rabbitmq

  rabbitmq:
    queues:
      storage: coral.storage.outbox.facil
      notifications:
        inbox: coral.notificaciones.inbox
        ready: coral.notificaciones.ready

  url:
    frontend: ${FRONTEND_URL}
    password-reset: ${PASSWORD_RESET_URL}
    portal-socios: ${PORTAL_SOCIOS_URL}

  clients:
    storage:
      url: ${STORAGE_SERVICE_URL}
      api-key: ${STORAGE_API_KEY}
      aliases:
        default: ${APP_CLIENTS_STORAGE_ALIASES_DEFAULT}

    notifications:
      url: ${NOTIFICATIONS_SERVICE_URL}
      api-key: ${NOTIFICATIONS_API_KEY}
      aliases:
        default: ${APP_CLIENTS_NOTIFICATIONS_ALIASES_DEFAULT}
        aws-ses: ${APP_CLIENTS_NOTIFICATIONS_ALIASES_AWS_SES}
      templates:
        reset-password: ${APP_CLIENTS_NOTIFICATIONS_TEMPLATES_RESET_PASSWORD}
        reserva-creada: ${APP_CLIENTS_NOTIFICATIONS_TEMPLATES_RESERVA_CREADA}
        reserva-cancelada: ${APP_CLIENTS_NOTIFICATIONS_TEMPLATES_RESERVA_CANCELADA}

    gotenberg:
      url: ${GOTENBERG_URL}

  security:
    password-reset:
      expiration-minutes: 60

  banco:
    cie:
      bbva: ${BANCO_CIE_BBVA}

logging:
  level:
    com.coralclubes.facil: INFO