spring:
  config:
    activate:
      on-profile: prod

  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  datasource-replica:
    url: ${DB_REPLICA_URL}
    username: ${DB_REPLICA_USER}
    password: ${DB_REPLICA_PASS}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASS}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:true}

  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER}
    password: ${RABBIT_PASS}

app:
  messaging:
    provider: rabbitmq

  rabbitmq:
    queues:
      storage: coral.storage.outbox.facil
      notifications:
        inbox: coral.notificaciones.inbox
        ready: coral.notificaciones.ready

  url:
    frontend: ${FRONTEND_URL}
    password-reset: ${PASSWORD_RESET_URL}
    portal-socios: ${PORTAL_SOCIOS_URL}

  clients:
    storage:
      url: ${STORAGE_SERVICE_URL}
      api-key: ${STORAGE_API_KEY}
      alias: ${APP_CLIENTS_STORAGE_ALIAS:S3}

    notifications:
      url: ${NOTIFICATIONS_SERVICE_URL}
      api-key: ${NOTIFICATIONS_API_KEY}
      alias: ${APP_CLIENTS_NOTIFICATIONS_ALIAS:SES}
      templates:
        reset-password: ${APP_CLIENTS_NOTIFICATIONS_TEMPLATES_RESET_PASSWORD}
        reserva-creada: ${APP_CLIENTS_NOTIFICATIONS_TEMPLATES_RESERVA_CREADA}
        reserva-cancelada: ${APP_CLIENTS_NOTIFICATIONS_TEMPLATES_RESERVA_CANCELADA}

    checkout:
      url: ${CHECKOUT_SERVICE_URL}
      api-key: FACIL_4dkQZoLmzOZ2Ynob6GnIeYbPR3O0yyEq
      urls:
        portal-resv:
          redirect-success: ${PORTAL_RESV_REDIRECT_SUCCESS:http://localhost:4200/reserva/exito}
          redirect-failure: ${PORTAL_RESV_REDIRECT_FAILURE:http://localhost:4200/reserva/fallo}
          redirect-cancel: ${PORTAL_RESV_REDIRECT_CANCEL:http://localhost:4200/reserva/detalle}
      is-sandbox: true
      default-tipo-serie-recibo: 1235

    gotenberg:
      url: ${GOTENBERG_URL}

  security:
    password-reset:
      expiration-minutes: 60

  banco:
    cie:
      bbva: ${BANCO_CIE_BBVA}

  crm:
    provider: ${CRM_PROVIDER:zoho}
    zoho:
      webhook-url: ${ZOHO_EVENTS_WEBHOOK_URL}

  email:
    audit-default: ${EMAIL_AUDIT_DEFAULT:facil@coralclubes.com}
    reservations: ${EMAIL_RESERVATIONS:reservaciones@coralclubes.com}

logging:
  level:
    com.coralclubes.facil: DEBUG